import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const secret=(process.env.BRIDGE_SECRET||fs.readFileSync(path.join(root,'server-data','bridge-secret.txt'),'utf8')).trim();
const api=process.env.API_BASE||'http://127.0.0.1:8787';
const [groupId='1058380864',qqId='2820758373',playerName='测试玩家',durationSeconds='15',difficulty='easy']=process.argv.slice(2);
const r=await fetch(api+'/api/rooms',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+secret},body:JSON.stringify({groupId,qqId,playerName,durationSeconds:Number(durationSeconds),difficulty})});
const result=await r.json();if(!r.ok)throw Error(JSON.stringify(result));
console.log('房间已创建（通信测试，不发放好感度）');console.log('打开链接：'+result.roomUrl);console.log('房间 ID：'+result.id);console.log('难度：'+result.difficulty);
